# Generated by Django 3.0.6 on 2020-05-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('winery', models.CharField(max_length=200)),
                ('crawl_date', models.DateTimeField(verbose_name='Date of price')),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
